### ISSUE TITLE
Error to install

### ISSUE THREAD

**Issue by component17** [layershift/rocketchat-jps#4]
"result":4109,
   "responses":[  
      {  
         "result":4109,
         "source":"JEL",
         "error":"The operation could not be performed. sed: can't read /opt/repo/supervisor.d/rocketchat.ini: No such file or directory\nsed: can't read /opt/repo/supervisor.d/rocketchat.ini: No such file or directory\nsed: can't read /opt/repo/supervisor.d/rocketchat.ini: No such file or directory\nsed: can't read /opt/repo/supervisor.d/rocketchat.ini: No such file or directory",
         "errOut":"sed: can't read /opt/repo/supervisor.d/rocketchat.ini: No such file or directory\nsed: can't read /opt/repo/supervisor.d/rocketchat.ini: No such file or directory\nsed: can't read /opt/repo/supervisor.d/rocketchat.ini: No such file or directory\nsed: can't read /opt/repo/supervisor.d/rocketchat.ini: No such file or directory",
         "nodeid":150790,
         "exitStatus":2,
         "out":""
      },
      {  
         "result":4109,
         "source":"JEL",
         "error":"The operation could not be performed. sed: can't read /opt/repo/supervisor.d/rocketchat.ini: No such file or directory\nsed: can't read /opt/repo/supervisor.d/rocketchat.ini: No such file or directory\nsed: can't read /opt/repo/supervisor.d/rocketchat.ini: No such file or directory\nsed: can't read /opt/repo/supervisor.d/rocketchat.ini: No such file or directory",
         "errOut":"sed: can't read /opt/repo/supervisor.d/rocketchat.ini: No such file or directory\nsed: can't read /opt/repo/supervisor.d/rocketchat.ini: No such file or directory\nsed: can't read /opt/repo/supervisor.d/rocketchat.ini: No such file or directory\nsed: can't read /opt/repo/supervisor.d/rocketchat.ini: No such file or directory",
         "nodeid":150792,
         "exitStatus":2,
         "out":""
      }
   ],
   "methodName":"execCmdByType",
   "action":"configureRocketChat.executeShellCommands",
   "source":"JEL",
   "error":"The operation could not be performed",
   "__info":{  
      "params":{  
         "appid":"appstore",
         "script":"InstallApp",
         "id":"rocketchat",
         "external":false,
         "settings":"{}",
         "shortdomain":"rocket",
         "actionkey":"1524660042830;installapp;rocket;rocketchat;-;install;1524660042823;Rocket.Chat (0.54.0);default_hn_group;jelastic.regruhosting.ru;false",
         "type":"nodejs",
         "version":"0.54.0",
         "name":"Rocket.Chat (0.54.0)",
         "displayName":"Rocket.Chat (0.54.0)",
         "manifest":"http://app.jelastic.regruhosting.ru/xssu/rest/download/RTYYHFJvU1VVVFkaNQM7R0UXAEIJTxVDWhQ5HH9yfgEVQBEFDwIEQmNTTEBI",
         "region":"default_hn_group",
         "charset":"UTF-8",
         "hx_lang":"ru",
         "session":"8e2dx158f9bdc787e5334c2b2a0c181c8c9f7",
         "ruk":"87f7866f-4881-441f-bc25-tab630279",
         "debug":{  
            "startTime":1524660042856,
            "duration":796014,
            "headers":{  
               "expires":"Wed, 25 Apr 2018 12:53:57 GMT",
               "x-resolver-ip":"151.248.124.254",
               "content-length":"1820",
               "content-type":"text/plain;charset=UTF-8",
               "connection":"keep-alive",
               "cache-control":"no-cache",
               "access-control-allow-origin":"*",
               "p3p":"CP='IDC DSP COR ADM DEVi TAIi PSA PSD IVAi IVDi CONi HIS OUR IND CNT'",
               "access-control-allow-methods":"GET, PUT, POST, DELETE, HEAD, OPTIONS",
               "content-language":"ru-RU",
               "server":"openresty/1.11.2.1",
               "date":"Wed, 25 Apr 2018 12:53:58 GMT"
            },
            "userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36",
            "method":"POST",
            "retriesCount":0,
            "requestId":1241,
            "httpStatus":200,
            "statusText":"OK",
            "responseText":"{\"result\":0,\"debug\":{\"cpu\":{\"usage\":\"0\",\"time\":3256},\"time\":795909},\"response\":{\"result\":4109,\"responses\":[{\"result\":4109,\"source\":\"JEL\",\"error\":\"The operation could not be performed. sed: can't read /opt/repo/supervisor.d/rocketchat.ini: No such file or directory\\nsed: can't read /opt/repo/supervisor.d/rocketchat.ini: No such file or directory\\nsed: can't read /opt/repo/supervisor.d/rocketchat.ini: No such file or directory\\nsed: can't read /opt/repo/supervisor.d/rocketchat.ini: No such file or...",
            "aborted":false,
            "timedout":false
         }
      },
      "url":"/1.0/development/scripting/rest/eval",
      "startTime":1524660042856,
      "duration":796014,
      "headers":{  
         "expires":"Wed, 25 Apr 2018 12:53:57 GMT",
         "x-resolver-ip":"151.248.124.254",
         "content-length":"1820",
         "content-type":"text/plain;charset=UTF-8",
         "connection":"keep-alive",
         "cache-control":"no-cache",
         "access-control-allow-origin":"*",
         "p3p":"CP='IDC DSP COR ADM DEVi TAIi PSA PSD IVAi IVDi CONi HIS OUR IND CNT'",
         "access-control-allow-methods":"GET, PUT, POST, DELETE, HEAD, OPTIONS",
         "content-language":"ru-RU",
         "server":"openresty/1.11.2.1",
         "date":"Wed, 25 Apr 2018 12:53:58 GMT"
      }
   }
}

**Comment by bubbl** [comment]
HI, thanks for that, this should be fixed now.
